### ISSUE TITLE
Update the website's title and branding.

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#11]
Description: Replace "FitLife Gym" with "Shubham Ghaturle".

**Comment by Saifkhan-rkp** [comment]
Hello @Shubhuscode I would like to work on this issue, please ensure with your replay that this issue is still open or have taken by any other person?

**Comment by shubham-ghaturle01** [comment]
Hello @Saifkhan-rkp ,
Yes, the issue is still open, and no one else has taken it yet. Please make sure to take the latest pull from the repository before starting your work. Feel free to proceed!

**Comment by Saifkhan-rkp** [comment]
@Shubhuscode Should i change all occurrences of "FitLife Gym" with "Shubham Ghaturle" ? or just in title of the site?

**Comment by shubham-ghaturle01** [comment]
Hi @Saifkhan-rkp ,
Yes, please change all occurrences of "FitLife Gym" to "Shubham Ghaturle" throughout the entire project, not just the title of the site. This will ensure consistency across all sections.

**Comment by Saifkhan-rkp** [comment]
Okay @Shubhuscode , I'll change accordingly.

**Comment by Saifkhan-rkp** [comment]
@Shubhuscode I have created PR, review the change of PR #25.

**Comment by shubham-ghaturle01** [comment]
issue resolved by @Saifkhan-rkp  #25 .
