### ISSUE TITLE
Update the hero section with your personal tagline and image.

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#12]
Replace "Transform Your Body, Transform Your Life" with "Welcome to My Portfolio".
 
 Replace "Join FitLife Gym today for a healthier tomorrow!" with " Showcasing My Skills and Projects".
 
 update button  "Get started" to  "Contact Me".
 
Replace Background image  ;-

![hero_background](https://github.com/user-attachments/assets/a4464cb1-00e4-44ce-b181-868bb407b5a9)

**Comment by Saifkhan-rkp** [comment]
@Shubhuscode I would like to work on this issue as well, if anyone hasn't taken i'll taking this.

**Comment by Saifkhan-rkp** [comment]
Hey @Shubhuscode , Is there any changes to do into the CSS file along with above mention changes?

**Comment by shubham-ghaturle01** [comment]
Hi @Saifkhan-rkp ,
Thank you for the update! I see that the changes have been made in the hero section. I will review them and proceed accordingly.
