### ISSUE TITLE
Replace About Us Section with Personal Information

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#13]
1. replace  "About Us" with "About Me".
2.  Change the content  with "Hi, I'm Shubham Ghaturle. I specialize in Java development. I have experience in building scalable and efficient applications, and I'm passionate about coding and solving complex problems."

**Comment by MuktaTiwari** [comment]
Hii @Shubhuscode 
I would like to handle these things, so can I do it?

**Comment by shubham-ghaturle01** [comment]
Hi @MuktaTiwari ,
I’d be happy to take care of this. Please ensure it’s done in a single commit and follow the contribution guidelines in the README. Feel free to reach out if you need any assistance.
