### ISSUE TITLE
Update the portfolio section to showcase your personal projects instead of gym images.

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#14]
Replace the gym-related images with below images.

![img1](https://github.com/user-attachments/assets/83983229-be31-469a-a5f3-a42158ba8cc0)

![img2](https://github.com/user-attachments/assets/6cdb3c86-546a-4339-ac88-6e83b2650890)

![img3](https://github.com/user-attachments/assets/433024d7-10bb-425b-904d-b5c78c66ddf0)

![img4](https://github.com/user-attachments/assets/4f84482b-5fa3-433d-93e1-438b2ca812c6)

**Comment by kambleaishwarya** [comment]
Hi Shubham, I would like to take up this issue. If you permit, please comment  Accordingly, I will start working on it.

**Comment by shubham-ghaturle01** [comment]
Hi @kambleaishwarya  ,
I’d be happy to take care of this. Please ensure it’s done in a single commit and follow the contribution guidelines in the README. Feel free to reach out if you need any assistance.

**Comment by kambleaishwarya** [comment]
Hi Shubham, I have made the required changes and created a pull request. Please have a look.

**Comment by shubham-ghaturle01** [comment]
hello @kambleaishwarya ,
Great! The new images have been added, but the old unused images are still present. Please remove them to keep the project clean.
