### ISSUE TITLE
Update Our Packages (Services ) Section with Skills/Expertise

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#15]
1. Replace the heading "Our Packages" with "our services".

2. replace the services heading and description with below 
   i) Web Development
     description :- HTML, CSS, JavaScript, React, Node.js
   ii) UI/UX Design
     description :- Sketch, Figma, Adobe XD
   iii) Graphic Design 
      description :- Photoshop, Illustrator, Branding

4.Fee Removed: Deleted all references to fees from the service cards.

5.Button Replaced: Replaced the Subscribe button with a Contact Me anchor link, redirecting to #contact.

**Comment by keshav-09** [comment]
Hi @Shubhuscode , I would like to work on this issue. Is anyone else already working on it, or can I start working on it?

**Comment by shubham-ghaturle01** [comment]
Hi @keshav-09  ,
I’d be happy to take care of this. Please ensure it’s done in a single commit and follow the contribution guidelines in the README. Feel free to reach out if you need any assistance.
