### ISSUE TITLE
 Contact Form Validation with SweetAlert2

### ISSUE THREAD

**Issue by shubham-ghaturle01** [Shubhuscode/gym_website#20]
Currently, the contact form in the "Contact Us" section is implemented with basic validation and uses SweetAlert2 for showing success or error messages. However, there are some potential improvements and fixes to consider

**Comment by MuktaTiwari** [comment]
Hii @Shubhuscode 
I would like to handle this task so, with your permission can I do this?
please give me the details of improvements you want here

**Comment by shubham-ghaturle01** [comment]
Hi @MuktaTiwari ,

Go ahead! You can proceed with the task. Let me know if you need any further details or assistance.
